CXX         = g++-11
CXXFLAGS    = -O3 -march=native -std=c++11



default: templating_01

templating_01: templating_01.cpp
	$(CXX) $(CXXFLAGS) -o templating_01 templating_01.cpp


clean:
	rm -rf templating_01
